#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# AUTO-GENERATED WORKFLOWS FOR DOMAIN: fileorg
# DO NOT EDIT THIS FILE MANUALLY. UPDATE domain.json AND RECOMPILE.
import sys
import logging

def run_scan_to_diff(args):
    """Standard flow to ingest data and compare states."""
    print(f"--- Executing Workflow: scan-to-diff ---")
    # Node: step_ingest (@core.fs.scan)
    from dcomp.core.fs.noun import scan as dido_step_ingest
    scan_context = dido_step_ingest(target=getattr(args, 'working_dir', None))

    # Node: step_compare (@fileorg.diff)
    from dcomp.fileorg.verbs.diff import diff as dido_step_compare
    diff_report = dido_step_compare(left=scan_context, right=getattr(args, 'remote', None))

    print(f"--- Workflow scan-to-diff complete. ---")

def run_scene_sync(args):
    """Full lifecycle: Scan -> Detect -> Sync."""
    print(f"--- Executing Workflow: scene-sync ---")
    # Node: ingest (@core.fs.scan)
    from dcomp.core.fs.noun import scan as dido_ingest
    raw_data = dido_ingest()

    # Node: analyze (@fileorg.scene.detect)
    from dcomp.fileorg.scene.noun import detect as dido_analyze
    scenes = dido_analyze(context=raw_data)

    # Node: comparison (@fileorg.diff)
    from dcomp.fileorg.verbs.diff import diff as dido_comparison
    diff = dido_comparison(left=scenes, right=getattr(args, 'remote', None))

    # Node: plan (@fileorg.sync)
    from dcomp.fileorg.verbs.sync import sync as dido_plan
    manifest = dido_plan(diff_data=diff)

    print(f"--- Workflow scene-sync complete. ---")

def run_test_workflow(args):
    """Auto-wired workflow: @test_domain.camera.scan | @test_domain.camera.process"""
    print(f"--- Executing Workflow: test_workflow ---")
    # Node: step_1 (@test_domain.camera.scan)
    from dcomp.test_domain.camera.noun import scan as dido_step_1
    dido_step_1(target=getattr(args, 'target', None))

    # Node: step_2 (@test_domain.camera.process)
    from dcomp.test_domain.camera.noun import process as dido_step_2
    step_2_data = dido_step_2(incoming_stream=step_1)

    print(f"--- Workflow test_workflow complete. ---")
